version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mainline.proxy.rlwy.net
      - PMA_PORT=46146
      - PMA_USER=root
      - PMA_PASSWORD=edOYTesFehunrDpmkjVvogCPdRctBXbh